
export const tableData = [
    {
      id: 1,
      date: "2023-01-01",
      user: "John Doe",
      materials: "Daging Ayam",
      quantities: "10",
      unit: "Kg",
    },
    {
      id: 2,
      date: "2023-01-01",
      user: "John Doe",
      materials: "Daging Sapi",
      quantities: "5",
      unit: "Kg",
    },
    {
        id: 3,
        date: "2023-01-01",
        user: "John Doe",
        materials: "Daging Sapi",
        quantities: "5",
        unit: "Kg",
      },
      {
        id: 4,
        date: "2023-01-01",
        user: "John Doe",
        materials: "Daging Sapi",
        quantities: "5",
        unit: "Kg",
      },
      {
        id: 5,
        date: "2023-01-01",
        user: "Jake Miller",
        materials: "Daging Sapi",
        quantities: "5",
        unit: "Kg",
      },
      {
        id: 6,
        date: "2023-01-01",
        user: "John Doe",
        materials: "Daging Sapi",
        quantities: "5",
        unit: "Kg",
      },
      {
        id: 7,
        date: "2023-01-01",
        user: "John Doe",
        materials: "Daging Sapi",
        quantities: "5",
        unit: "Kg",
      },
      {
        id: 8,
        date: "2023-01-01",
        user: "John Doe",
        materials: "Daging Sapi",
        quantities: "5",
        unit: "Kg",
      },
      {
        id: 9,
        date: "2023-01-01",
        user: "John Doe",
        materials: "Daging Sapi",
        quantities: "5",
        unit: "Kg",
      },
      {
        id: 10,
        date: "2023-01-01",
        user: "John Doe",
        materials: "Daging Sapi",
        quantities: "5",
        unit: "Kg",
      },
      {
        id: 11,
        date: "2023-01-01",
        user: "John Doe",
        materials: "Daging Sapi",
        quantities: "5",
        unit: "Kg",
      },
]
    
